/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.DepartmentControl;
import control.RuanganControl;
import exception.InputKosongException;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Department;
import model.Ruangan;
import table.TableRuangan;


/**
 *
 * @author henry
 */
public class RuanganView extends javax.swing.JFrame {
    private DepartmentControl departmentControl;
    private RuanganControl ruanganControl;
    String action = "tambah";
    int selectedId = 0;
    
    List<Department> listDepartment;
    List<Ruangan> listRuangan;
    
    /**
     * Creates new form GajiView
     */
    public RuanganView() {
        initComponents();
        departmentControl = new DepartmentControl();
        ruanganControl = new RuanganControl();
        InputRuangan.setEnabled(false);
        showRuangan();
        setDepartmentToDropdown();
    }
    
    public void showRuangan(){
        lastID();
        tabelRuangan.setModel(ruanganControl.showDataRuangan(""));
    }
    
    public void inputKosongException() throws InputKosongException{
        if(InputRuangan.getText().isEmpty()){
            throw new InputKosongException();
        }else if(Inputharga.getText().isEmpty()){
            throw new InputKosongException();
        }else if(inputTipeR.getText().isEmpty()){
            throw new InputKosongException();
        }else if(Inputfasilitas.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    
    public void clearText(){
        DComboBox.setSelectedItem(ABORT);
        InputRuangan.setText("");
        Inputharga.setText("");
        inputTipeR.setText("");
        Inputfasilitas.setText("");   
    }
    
    public void lastID(){
        listRuangan =  ruanganControl.showListRuangan();
        
        int i=0;
        for(Ruangan r : listRuangan){
            i = r.getNo();
        }
        InputRuangan.setText(String.valueOf(i+1));
    }
    
    public void resetButton(){
        buttonTambah.setText("Tambah");
        buttonTambah.setBackground(new Color(51,102,255));
    }
      
    public void setDepartmentToDropdown(){
        listDepartment = departmentControl.showListDepartment();
        for (int i = 0; i < listDepartment.size(); i++) {
            DComboBox.addItem(listDepartment.get(i));
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelJenisPenyakit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelDepartment = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelDokter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelPasien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelRuangan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelTransaksi = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelHistoriTransaksi = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelTampilGaji = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelHistoriGaji = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelNo = new javax.swing.JLabel();
        ruanganLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelGajiDokter5 = new javax.swing.JLabel();
        inputTipeR = new javax.swing.JTextField();
        labelharga = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        Inputharga = new javax.swing.JTextField();
        buttonBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRuangan = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        labeldaftarR = new javax.swing.JLabel();
        InputRuangan = new javax.swing.JTextField();
        labelharga1 = new javax.swing.JLabel();
        Inputfasilitas = new javax.swing.JTextField();
        DComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn1 = new javax.swing.JButton();
        delete = new javax.swing.JLabel();

        searchBtn.setBackground(new java.awt.Color(0, 153, 204));
        searchBtn.setText("Cari");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(224, 224, 224));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Siloam");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Hospital");

        panelJenisPenyakit.setBackground(new java.awt.Color(224, 224, 224));
        panelJenisPenyakit.setPreferredSize(new java.awt.Dimension(170, 30));
        panelJenisPenyakit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelJenisPenyakitMouseMoved(evt);
            }
        });
        panelJenisPenyakit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelJenisPenyakitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelJenisPenyakitMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jenis Penyakit");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelJenisPenyakitLayout = new javax.swing.GroupLayout(panelJenisPenyakit);
        panelJenisPenyakit.setLayout(panelJenisPenyakitLayout);
        panelJenisPenyakitLayout.setHorizontalGroup(
            panelJenisPenyakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJenisPenyakitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJenisPenyakitLayout.setVerticalGroup(
            panelJenisPenyakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJenisPenyakitLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        panelDepartment.setBackground(new java.awt.Color(224, 224, 224));
        panelDepartment.setPreferredSize(new java.awt.Dimension(170, 30));
        panelDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDepartmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDepartmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDepartmentMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Department");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDepartmentLayout = new javax.swing.GroupLayout(panelDepartment);
        panelDepartment.setLayout(panelDepartmentLayout);
        panelDepartmentLayout.setHorizontalGroup(
            panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelDepartmentLayout.setVerticalGroup(
            panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDepartmentLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panelDokter.setBackground(new java.awt.Color(224, 224, 224));
        panelDokter.setPreferredSize(new java.awt.Dimension(170, 30));
        panelDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDokterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDokterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDokterMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dokter");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDokterLayout = new javax.swing.GroupLayout(panelDokter);
        panelDokter.setLayout(panelDokterLayout);
        panelDokterLayout.setHorizontalGroup(
            panelDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDokterLayout.setVerticalGroup(
            panelDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDokterLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        panelPasien.setBackground(new java.awt.Color(224, 224, 224));
        panelPasien.setPreferredSize(new java.awt.Dimension(170, 30));
        panelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPasienMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pasien");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPasienLayout = new javax.swing.GroupLayout(panelPasien);
        panelPasien.setLayout(panelPasienLayout);
        panelPasienLayout.setHorizontalGroup(
            panelPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPasienLayout.setVerticalGroup(
            panelPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasienLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelRuangan.setBackground(new java.awt.Color(255, 255, 255));
        panelRuangan.setPreferredSize(new java.awt.Dimension(170, 30));
        panelRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRuanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRuanganMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ruangan");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRuanganLayout = new javax.swing.GroupLayout(panelRuangan);
        panelRuangan.setLayout(panelRuanganLayout);
        panelRuanganLayout.setHorizontalGroup(
            panelRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRuanganLayout.setVerticalGroup(
            panelRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRuanganLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Input");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Transaksi Pasien");

        panelTransaksi.setBackground(new java.awt.Color(224, 224, 224));
        panelTransaksi.setPreferredSize(new java.awt.Dimension(170, 30));
        panelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTransaksiMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Transaksi");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        panelHistoriTransaksi.setBackground(new java.awt.Color(224, 224, 224));
        panelHistoriTransaksi.setPreferredSize(new java.awt.Dimension(170, 30));
        panelHistoriTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHistoriTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHistoriTransaksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHistoriTransaksiLayout = new javax.swing.GroupLayout(panelHistoriTransaksi);
        panelHistoriTransaksi.setLayout(panelHistoriTransaksiLayout);
        panelHistoriTransaksiLayout.setHorizontalGroup(
            panelHistoriTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        panelHistoriTransaksiLayout.setVerticalGroup(
            panelHistoriTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Gaji Dokter");

        panelTampilGaji.setBackground(new java.awt.Color(224, 224, 224));
        panelTampilGaji.setPreferredSize(new java.awt.Dimension(170, 30));
        panelTampilGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTampilGajiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTampilGajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTampilGajiMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tampil Gaji");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTampilGajiLayout = new javax.swing.GroupLayout(panelTampilGaji);
        panelTampilGaji.setLayout(panelTampilGajiLayout);
        panelTampilGajiLayout.setHorizontalGroup(
            panelTampilGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTampilGajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panelTampilGajiLayout.setVerticalGroup(
            panelTampilGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTampilGajiLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        panelHistoriGaji.setBackground(new java.awt.Color(224, 224, 224));
        panelHistoriGaji.setPreferredSize(new java.awt.Dimension(170, 30));
        panelHistoriGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHistoriGajiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHistoriGajiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHistoriGajiLayout = new javax.swing.GroupLayout(panelHistoriGaji);
        panelHistoriGaji.setLayout(panelHistoriGajiLayout);
        panelHistoriGajiLayout.setHorizontalGroup(
            panelHistoriGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        panelHistoriGajiLayout.setVerticalGroup(
            panelHistoriGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelJenisPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelHistoriTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelTampilGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(panelHistoriGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJenisPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistoriTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTampilGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistoriGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNo.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        labelNo.setForeground(new java.awt.Color(153, 153, 153));
        labelNo.setText("No Ruangan");

        ruanganLabel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ruanganLabel.setText("Ruangan");

        labelGajiDokter5.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        labelGajiDokter5.setForeground(new java.awt.Color(153, 153, 153));
        labelGajiDokter5.setText("Tipe Ruangan");

        inputTipeR.setAlignmentX(50.0F);
        inputTipeR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        inputTipeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipeRActionPerformed(evt);
            }
        });

        labelharga.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        labelharga.setForeground(new java.awt.Color(153, 153, 153));
        labelharga.setText("Harga Ruangan");

        buttonTambah.setBackground(new java.awt.Color(51, 102, 255));
        buttonTambah.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.setBorder(null);
        buttonTambah.setBorderPainted(false);
        buttonTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        Inputharga.setAlignmentX(50.0F);
        Inputharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Inputharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputhargaActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(255, 51, 51));
        buttonBatal.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("Batal");
        buttonBatal.setBorder(null);
        buttonBatal.setBorderPainted(false);
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        tabelRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRuangan);

        labeldaftarR.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labeldaftarR.setForeground(new java.awt.Color(20, 20, 20));
        labeldaftarR.setText("Daftar Ruangan");

        InputRuangan.setAlignmentX(50.0F);
        InputRuangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        InputRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRuanganActionPerformed(evt);
            }
        });

        labelharga1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        labelharga1.setForeground(new java.awt.Color(153, 153, 153));
        labelharga1.setText("Fasilitas Ruangan");

        Inputfasilitas.setAlignmentX(50.0F);
        Inputfasilitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Inputfasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputfasilitasActionPerformed(evt);
            }
        });

        DComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Departmenet");

        searchBtn1.setBackground(new java.awt.Color(0, 153, 204));
        searchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn1.setText("Cari");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        delete.setForeground(new java.awt.Color(255, 0, 51));
        delete.setText("Hapus");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(delete))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                        .addComponent(jSeparator2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InputRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelharga, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelGajiDokter5)
                                .addComponent(inputTipeR, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labeldaftarR)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Inputharga, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Inputfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ruanganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ruanganLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNo)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelGajiDokter5)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTipeR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelharga)
                    .addComponent(labelharga1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inputharga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inputfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(DComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeldaftarR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        try{
            inputKosongException();
            
            int selectedIndexDepartment = DComboBox.getSelectedIndex();
            Department selectedDepartment = listDepartment.get(selectedIndexDepartment);
            
            if(action.equals("edit")){
                Ruangan r = new Ruangan(Integer.parseInt(InputRuangan.getText()), inputTipeR.getText(), Double.parseDouble(Inputharga.getText()), Inputfasilitas.getText(), selectedDepartment);
                ruanganControl.updateDataRuangan(r);
            }else if(action.equals("tambah")){
                Ruangan r = new Ruangan(inputTipeR.getText(), Double.parseDouble(Inputharga.getText()), Inputfasilitas.getText(), selectedDepartment);
                ruanganControl.insertDataRuangan(r);
            }
             
           clearText();
           resetButton();
           showRuangan();
           
        } catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void inputTipeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipeRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipeRActionPerformed

    private void panelJenisPenyakitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelJenisPenyakitMouseMoved
        
    }//GEN-LAST:event_panelJenisPenyakitMouseMoved

    private void panelJenisPenyakitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelJenisPenyakitMouseExited
        
    }//GEN-LAST:event_panelJenisPenyakitMouseExited

    private void panelDepartmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDepartmentMouseEntered
        panelDepartment.setBackground(Color.white);
    }//GEN-LAST:event_panelDepartmentMouseEntered

    private void panelDepartmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDepartmentMouseExited
        panelDepartment.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelDepartmentMouseExited

    private void panelDokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDokterMouseEntered
        panelDokter.setBackground(Color.white);
    }//GEN-LAST:event_panelDokterMouseEntered

    private void panelDokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDokterMouseExited
        panelDokter.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelDokterMouseExited

    private void panelPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPasienMouseEntered
        panelPasien.setBackground(Color.white);
    }//GEN-LAST:event_panelPasienMouseEntered

    private void panelPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPasienMouseExited
        panelPasien.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelPasienMouseExited

    private void panelRuanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRuanganMouseEntered
        panelRuangan.setBackground(Color.white);
    }//GEN-LAST:event_panelRuanganMouseEntered

    private void panelRuanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRuanganMouseExited
        panelRuangan.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelRuanganMouseExited

    private void panelTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransaksiMouseEntered
        panelTransaksi.setBackground(Color.white);
    }//GEN-LAST:event_panelTransaksiMouseEntered

    private void panelTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransaksiMouseExited
        panelTransaksi.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelTransaksiMouseExited

    private void panelHistoriTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistoriTransaksiMouseEntered
        panelHistoriTransaksi.setBackground(Color.white);
    }//GEN-LAST:event_panelHistoriTransaksiMouseEntered

    private void panelHistoriTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistoriTransaksiMouseExited
        panelHistoriTransaksi.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelHistoriTransaksiMouseExited

    private void panelTampilGajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTampilGajiMouseEntered
        panelTampilGaji.setBackground(Color.white);
    }//GEN-LAST:event_panelTampilGajiMouseEntered

    private void panelTampilGajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTampilGajiMouseExited
        panelTampilGaji.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelTampilGajiMouseExited

    private void panelHistoriGajiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistoriGajiMouseEntered
        panelHistoriGaji.setBackground(Color.white);
    }//GEN-LAST:event_panelHistoriGajiMouseEntered

    private void panelHistoriGajiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHistoriGajiMouseExited
        panelHistoriGaji.setBackground(Color.getColor("E0E0E0"));
    }//GEN-LAST:event_panelHistoriGajiMouseExited

    private void InputhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputhargaActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        clearText();
        resetButton();
        lastID();
        showRuangan();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void InputRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputRuanganActionPerformed

    private void InputfasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputfasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputfasilitasActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
//        setEditDeleteBtn(false);
//        
//        setComponent(false);
//        
//        try{
//            TableRuangan ruangan = ruanganControl.showDataRuangan(searchField.getText());
//            
//            if(ruangan.getRowCount() == 0){
//                clearText();
//                setEditDeleteBtn(false);
//                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "konfirmasi", JOptionPane.DEFAULT_OPTION);
//            }else{
//                tabelRuangan.setModel(ruangan);
//            }
//            
//            clearText();
//        }catch (Exception e){
//            System.out.println("Error : " + e.getMessage());
//        }
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void tabelRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRuanganMouseClicked
        int indexDepartment = -1;
        
        int clickedRow = tabelRuangan.getSelectedRow();
        TableModel tableModel = tabelRuangan.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        Inputharga.setText(tableModel.getValueAt(clickedRow, 2).toString());
        inputTipeR.setText(tableModel.getValueAt(clickedRow, 1).toString());
        Inputfasilitas.setText(tableModel.getValueAt(clickedRow, 3).toString());
        
        listRuangan = ruanganControl.showListRuangan();
        
        String id_dp = tableModel.getValueAt(clickedRow, 0).toString();
        for(Department dp : listDepartment){
            if(dp.getId() == Integer.parseInt(id_dp)) {
                indexDepartment = listDepartment.indexOf(dp);
            }
        }
        DComboBox.setSelectedIndex(indexDepartment);
        
        for(Ruangan r : listRuangan){
            System.out.println(selectedId + " - " + r.getNo());
            if(selectedId == r.getNo()){
                action = "edit";
                buttonTambah.setText("Edit");
                buttonTambah.setBackground(new Color(255, 153, 0));
                break;
            }else{
                action = "tambah";
            }
        }
       
    }//GEN-LAST:event_tabelRuanganMouseClicked

    private void DComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DComboBoxActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menghapus data ? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        switch(getAnswer){
            case 0:

            try{
                ruanganControl.deleteDataRuangan(selectedId);
                clearText();
                showRuangan();

            }catch (Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;
            case 1:

            break;
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void panelJenisPenyakitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelJenisPenyakitMouseClicked
        JenisPenyakitView jp = new JenisPenyakitView();
        this.dispose();
        jp.setVisible(true);
    }//GEN-LAST:event_panelJenisPenyakitMouseClicked

    private void panelDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDepartmentMouseClicked
        DepartmentView dv = new DepartmentView();
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_panelDepartmentMouseClicked

    private void panelDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDokterMouseClicked
        DokterView dkv = new DokterView();
        this.dispose();
        dkv.setVisible(true);
    }//GEN-LAST:event_panelDokterMouseClicked

    private void panelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransaksiMouseClicked
        TransaksiView tv = new TransaksiView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_panelTransaksiMouseClicked

    private void panelTampilGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTampilGajiMouseClicked
        GajiView gv = new GajiView();
        this.dispose();
        gv.setVisible(true);
    }//GEN-LAST:event_panelTampilGajiMouseClicked

    private void panelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPasienMouseClicked
        PasienView p = new PasienView ();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_panelPasienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuanganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuanganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuanganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuanganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuanganView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Department> DComboBox;
    private javax.swing.JTextField InputRuangan;
    private javax.swing.JTextField Inputfasilitas;
    private javax.swing.JTextField Inputharga;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel delete;
    private javax.swing.JTextField inputTipeR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelGajiDokter5;
    private javax.swing.JLabel labelNo;
    private javax.swing.JLabel labeldaftarR;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel labelharga1;
    private javax.swing.JPanel panelDepartment;
    private javax.swing.JPanel panelDokter;
    private javax.swing.JPanel panelHistoriGaji;
    private javax.swing.JPanel panelHistoriTransaksi;
    private javax.swing.JPanel panelJenisPenyakit;
    private javax.swing.JPanel panelPasien;
    private javax.swing.JPanel panelRuangan;
    private javax.swing.JPanel panelTampilGaji;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JLabel ruanganLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tabelRuangan;
    // End of variables declaration//GEN-END:variables
}
