/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.DokterControl;
import control.TransaksiControl;
import control.PasienControl;
import control.RuanganControl;
import control.DepartmentControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Dokter;
import model.Transaksi;
import model.Pasien;
import model.Ruangan;
import model.Department;
import model.Jenis_Penyakit;
import table.TableTransaksi;

/**
 * Kelompok 5 :
 * 200710534 - Nicholas Suharto
 * 200710587 - Aldyo Putra
 * 200710607 - Henry
 * 200710653 - Tia Vianka Yustin
 * 200710681 - Kenneth Vincentius Theys
**/
public class TransaksiView extends javax.swing.JFrame {
    
    private DokterControl dokterControl;
    private TransaksiControl transaksiControl;
    private PasienControl pasienControl;
    private RuanganControl ruanganControl;
    //private DepartmentControl ruanganControl;
    String action = null;
    List<Dokter> listDokter;
    List<Pasien> listPasien;
    List<Transaksi> listTransaksi;
    int selectedId = 0;
   
    public TransaksiView() {
        initComponents();
        setComponent(false);
        dokterControl = new DokterControl();
        transaksiControl = new TransaksiControl();
        pasienControl = new PasienControl();
        ruanganControl = new RuanganControl();
        showTransaksi();
    }
//    
    public void setComponent(boolean value) {
        addBtn.setEnabled(value);
        saveBtn.setEnabled(value);
    }
//    
    public void clearText() {
        idTransaksiTextField.setText("");
        tglTransaksiTextField.setText("");
        namaPasienTextField.setText("");
        umurPasienTextField.setText("");
        genderTextField.setText("");
        alamatTextField.setText("");
        noTeleponTextField.setText("");
        dokterPengampuTextField.setText("");
        biayaKamarTextField.setText("");
        biayaDokterTextField.setText("");
        biayaDiagnosisTextField.setText("");
    }
//    
    public void showTransaksi() {
        tableTransaksi.setModel(transaksiControl.showDataTransaksi(""));
    }
//    
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        headerPanel = new javax.swing.JPanel();
        rsPanel = new javax.swing.JPanel();
        RSLabel = new javax.swing.JLabel();
        judulPanel = new javax.swing.JPanel();
        mouseclickPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        dokterPanel = new javax.swing.JPanel();
        dokterLabel = new javax.swing.JLabel();
        pasienPanel = new javax.swing.JPanel();
        pasienLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        tableContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        systemPanel = new javax.swing.JPanel();
        detailContainer = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        leftGrid = new javax.swing.JPanel();
        namaPasienLabel = new javax.swing.JLabel();
        umurPasienLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        idTransaksiLabel = new javax.swing.JLabel();
        tglTransaksiLabel = new javax.swing.JLabel();
        noTeleponLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        idTransaksiTextField = new javax.swing.JTextField();
        tglTransaksiTextField = new javax.swing.JTextField();
        namaPasienTextField = new javax.swing.JTextField();
        umurPasienTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        noTeleponTextField = new javax.swing.JTextField();
        alamatTextField = new javax.swing.JTextField();
        rightGrid = new javax.swing.JPanel();
        biayaDiagnosisLabel = new javax.swing.JLabel();
        biayaKamarLabel = new javax.swing.JLabel();
        biayaDokterLabel = new javax.swing.JLabel();
        dokterPengampuLabel = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        dokterPengampuTextField = new javax.swing.JTextField();
        biayaKamarTextField = new javax.swing.JTextField();
        biayaDokterTextField = new javax.swing.JTextField();
        biayaDiagnosisTextField = new javax.swing.JTextField();
        totalBiayaTextField = new javax.swing.JTextField();
        identityPanel = new javax.swing.JPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        rsPanel.setBackground(new java.awt.Color(0, 204, 204));
        rsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RSLabel.setBackground(new java.awt.Color(0, 204, 204));
        RSLabel.setFont(new java.awt.Font("Castellar", 0, 22)); // NOI18N
        RSLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RSLabel.setText("rumah sakit");

        javax.swing.GroupLayout rsPanelLayout = new javax.swing.GroupLayout(rsPanel);
        rsPanel.setLayout(rsPanelLayout);
        rsPanelLayout.setHorizontalGroup(
            rsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rsPanelLayout.setVerticalGroup(
            rsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        judulPanel.setBackground(new java.awt.Color(0, 204, 204));

        mouseclickPanel.setBackground(new java.awt.Color(0, 204, 204));
        mouseclickPanel.setLayout(new java.awt.GridLayout(1, 0));

        adminPanel.setBackground(new java.awt.Color(0, 255, 153));
        adminPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMouseClicked(evt);
            }
        });

        adminLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        adminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/computer.png"))); // NOI18N
        adminLabel.setText("Admin");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(adminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(adminLabel)
                .addGap(14, 14, 14))
        );

        mouseclickPanel.add(adminPanel);

        dokterPanel.setBackground(new java.awt.Color(0, 255, 153));
        dokterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dokterPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterPanelMouseClicked(evt);
            }
        });

        dokterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        dokterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dokterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/transaksi.png"))); // NOI18N
        dokterLabel.setText("Dokter");

        javax.swing.GroupLayout dokterPanelLayout = new javax.swing.GroupLayout(dokterPanel);
        dokterPanel.setLayout(dokterPanelLayout);
        dokterPanelLayout.setHorizontalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(dokterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        dokterPanelLayout.setVerticalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dokterPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(dokterLabel)
                .addGap(15, 15, 15))
        );

        mouseclickPanel.add(dokterPanel);

        pasienPanel.setBackground(new java.awt.Color(0, 255, 153));
        pasienPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pasienPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasienPanelMouseClicked(evt);
            }
        });

        pasienLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        pasienLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/pembeli.png"))); // NOI18N
        pasienLabel.setText("Pasien");

        javax.swing.GroupLayout pasienPanelLayout = new javax.swing.GroupLayout(pasienPanel);
        pasienPanel.setLayout(pasienPanelLayout);
        pasienPanelLayout.setHorizontalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        pasienPanelLayout.setVerticalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasienPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pasienLabel)
                .addGap(14, 14, 14))
        );

        mouseclickPanel.add(pasienPanel);

        judulLabel.setBackground(new java.awt.Color(0, 204, 204));
        judulLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("TRANSAKSI");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mouseclickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mouseclickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(rsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containerPanel.setBackground(new java.awt.Color(204, 204, 204));

        tableContainer.setBackground(new java.awt.Color(204, 204, 204));

        tableTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        tableTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        javax.swing.GroupLayout tableContainerLayout = new javax.swing.GroupLayout(tableContainer);
        tableContainer.setLayout(tableContainerLayout);
        tableContainerLayout.setHorizontalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tableContainerLayout.setVerticalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        systemPanel.setBackground(new java.awt.Color(204, 204, 204));

        detailContainer.setBackground(new java.awt.Color(0, 0, 0));

        detailPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        detailPanel.setLayout(new java.awt.GridLayout(1, 0));

        leftGrid.setBackground(new java.awt.Color(255, 255, 255));

        namaPasienLabel.setBackground(new java.awt.Color(255, 255, 255));
        namaPasienLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        namaPasienLabel.setText("Nama Pasien");

        umurPasienLabel.setBackground(new java.awt.Color(255, 255, 255));
        umurPasienLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        umurPasienLabel.setText("Umur Pasien");

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        genderLabel.setText("Gender");

        idTransaksiLabel.setBackground(new java.awt.Color(255, 255, 255));
        idTransaksiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        idTransaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idTransaksiLabel.setText("Id Transaksi");

        tglTransaksiLabel.setBackground(new java.awt.Color(255, 255, 255));
        tglTransaksiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tglTransaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglTransaksiLabel.setText("Tgl Transaksi");

        noTeleponLabel.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        noTeleponLabel.setText("No Telepon");

        alamatLabel.setBackground(new java.awt.Color(255, 255, 255));
        alamatLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        alamatLabel.setText("Alamat");

        idTransaksiTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idTransaksiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTransaksiTextFieldActionPerformed(evt);
            }
        });

        tglTransaksiTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        namaPasienTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        umurPasienTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        genderTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        noTeleponTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        alamatTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout leftGridLayout = new javax.swing.GroupLayout(leftGrid);
        leftGrid.setLayout(leftGridLayout);
        leftGridLayout.setHorizontalGroup(
            leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftGridLayout.createSequentialGroup()
                        .addGroup(leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTransaksiLabel)
                            .addComponent(tglTransaksiLabel)
                            .addComponent(namaPasienLabel)
                            .addComponent(umurPasienLabel)
                            .addComponent(genderLabel)
                            .addComponent(noTeleponLabel)
                            .addComponent(alamatLabel))
                        .addGap(0, 372, Short.MAX_VALUE))
                    .addComponent(idTransaksiTextField)
                    .addComponent(tglTransaksiTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaPasienTextField)
                    .addComponent(umurPasienTextField)
                    .addComponent(genderTextField)
                    .addComponent(noTeleponTextField)
                    .addComponent(alamatTextField))
                .addContainerGap())
        );
        leftGridLayout.setVerticalGroup(
            leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTransaksiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(tglTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglTransaksiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(namaPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPasienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(umurPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurPasienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(noTeleponLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(alamatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        detailPanel.add(leftGrid);

        rightGrid.setBackground(new java.awt.Color(255, 255, 255));

        biayaDiagnosisLabel.setBackground(new java.awt.Color(255, 255, 255));
        biayaDiagnosisLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        biayaDiagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biayaDiagnosisLabel.setText("Biaya Diagnosis");

        biayaKamarLabel.setBackground(new java.awt.Color(255, 255, 255));
        biayaKamarLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        biayaKamarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biayaKamarLabel.setText("Biaya Kamar");

        biayaDokterLabel.setBackground(new java.awt.Color(255, 255, 255));
        biayaDokterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        biayaDokterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biayaDokterLabel.setText("Biaya Dokter");

        dokterPengampuLabel.setBackground(new java.awt.Color(255, 255, 255));
        dokterPengampuLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        dokterPengampuLabel.setText("Dokter Pengampu");

        totalBiayaLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalBiayaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        totalBiayaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBiayaLabel.setText("TOTAL BIAYA");

        saveBtn.setBackground(new java.awt.Color(0, 204, 255));
        saveBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 204, 255));
        addBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        dokterPengampuTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        biayaKamarTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        biayaDokterTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        biayaDiagnosisTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        totalBiayaTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        totalBiayaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBiayaTextField.setToolTipText("");

        javax.swing.GroupLayout rightGridLayout = new javax.swing.GroupLayout(rightGrid);
        rightGrid.setLayout(rightGridLayout);
        rightGridLayout.setHorizontalGroup(
            rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBiayaTextField)
                    .addComponent(totalBiayaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rightGridLayout.createSequentialGroup()
                        .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightGridLayout.createSequentialGroup()
                                .addGap(0, 257, Short.MAX_VALUE)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rightGridLayout.createSequentialGroup()
                                .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dokterPengampuLabel)
                                    .addComponent(biayaDokterLabel)
                                    .addComponent(biayaKamarLabel)
                                    .addComponent(biayaDiagnosisLabel)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(dokterPengampuTextField)
                    .addComponent(biayaDokterTextField)
                    .addComponent(biayaKamarTextField)
                    .addComponent(biayaDiagnosisTextField)))
        );
        rightGridLayout.setVerticalGroup(
            rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dokterPengampuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dokterPengampuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(biayaKamarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaKamarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(biayaDokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaDokterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(biayaDiagnosisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaDiagnosisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(totalBiayaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBiayaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(addBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        detailPanel.add(rightGrid);

        javax.swing.GroupLayout detailContainerLayout = new javax.swing.GroupLayout(detailContainer);
        detailContainer.setLayout(detailContainerLayout);
        detailContainerLayout.setHorizontalGroup(
            detailContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailContainerLayout.setVerticalGroup(
            detailContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout systemPanelLayout = new javax.swing.GroupLayout(systemPanel);
        systemPanel.setLayout(systemPanelLayout);
        systemPanelLayout.setHorizontalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, systemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        systemPanelLayout.setVerticalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        identityPanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout identityPanelLayout = new javax.swing.GroupLayout(identityPanel);
        identityPanel.setLayout(identityPanelLayout);
        identityPanelLayout.setHorizontalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        identityPanelLayout.setVerticalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(systemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(identityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMouseClicked
        AdminView av = new AdminView();
        this.dispose();
        av.setVisible(true);
    }//GEN-LAST:event_adminPanelMouseClicked

    private void pasienPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasienPanelMouseClicked
        PasienView pv = new PasienView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_pasienPanelMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
//        try{
//            int selectedIndex;
//
//            selectedIndex = computerDropdown.getSelectedIndex();
//            Computer selectedComputer = listComputer.get(selectedIndex);
//            selectedIndex = pembeliDropdown.getSelectedIndex();
//            Pembeli selectedPembeli = listPembeli.get(selectedIndex);
//
//            if(mouseCheckBox.isSelected()){ b1 = "Mouse, "; }
//            if(tasCheckBox.isSelected()){ b2 = "Tas, "; }
//            if(mousepadCheckBox.isSelected()){ b3 = "Mousepad"; }
//
//            if(action.equals("Tambah")){
//                Transaksi tr = new Transaksi(selectedId,tanggalInput.getText(),hargaInput.getText(),
//                    b1+b2+b3, selectedComputer, selectedPembeli);
//                transaksiControl.insertDataTransaksi(tr);
//            }
//            else
//            {
//                Transaksi tr = new Transaksi(selectedId,tanggalInput.getText(),hargaInput.getText(),
//                    b1+b2+b3, selectedComputer, selectedPembeli);
//                transaksiControl.updateDataTransaksi(tr);
//            }
//        } catch(InputKosongException e) {
//            JOptionPane.showMessageDialog(this, e.message());
//        }
//        clearText();
//        showTransaksi();
//        setComponent(false);
//
//        setEditDeleteBtn(false);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
//        int indexComputer = -1;
//        int indexPembeli = -1;
//        setEditDeleteBtn(true);
//
//        setComponent(false);
//
//        int clickedRow = tableTransaksi.getSelectedRow();
//        TableModel tableModel = tableTransaksi.getModel();
//
//        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
//        tanggalInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
//        hargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
//
//        String bonus = tableModel.getValueAt(clickedRow, 5).toString();
//        if((bonus.substring(0,1).equals("-")) == false)
//        {
//            mouseCheckBox.setSelected(true);
//        }
//        if(bonus.contains("Tas"))
//        {
//            tasCheckBox.setSelected(true);
//        }
//        if(bonus.contains("Mousepad"))
//        {
//            mousepadCheckBox.setSelected(true);
//        }
//
//        String id_c = tableModel.getValueAt(clickedRow, 9).toString();
//        for(Computer computer : listComputer){
//            if(computer.getID().equals(id_c)) {
//                indexComputer = listComputer.indexOf(computer);
//            }
//        }
//        computerDropdown.setSelectedIndex(indexComputer);
//
//        String id_p = tableModel.getValueAt(clickedRow, 10).toString();
//        for(Pembeli pembeli : listPembeli){
//            if(pembeli.getId() == Integer.parseInt(id_p)) {
//                indexPembeli = listPembeli.indexOf(pembeli);
//            }
//        }
//        pembeliDropdown.setSelectedIndex(indexPembeli);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void dokterPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterPanelMouseClicked
        DokterView dv = new DokterView();
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_dokterPanelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        
        clearText();
        action = "Tambah";
    }//GEN-LAST:event_addBtnActionPerformed

    private void idTransaksiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTransaksiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTransaksiTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RSLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JLabel biayaDiagnosisLabel;
    private javax.swing.JTextField biayaDiagnosisTextField;
    private javax.swing.JLabel biayaDokterLabel;
    private javax.swing.JTextField biayaDokterTextField;
    private javax.swing.JLabel biayaKamarLabel;
    private javax.swing.JTextField biayaKamarTextField;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel detailContainer;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel dokterLabel;
    private javax.swing.JPanel dokterPanel;
    private javax.swing.JLabel dokterPengampuLabel;
    private javax.swing.JTextField dokterPengampuTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel idTransaksiLabel;
    private javax.swing.JTextField idTransaksiTextField;
    private javax.swing.JPanel identityPanel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JPanel leftGrid;
    private javax.swing.JPanel mouseclickPanel;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JTextField namaPasienTextField;
    private javax.swing.JLabel noTeleponLabel;
    private javax.swing.JTextField noTeleponTextField;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JPanel pasienPanel;
    private javax.swing.JPanel rightGrid;
    private javax.swing.JPanel rsPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel systemPanel;
    private javax.swing.JPanel tableContainer;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel tglTransaksiLabel;
    private javax.swing.JTextField tglTransaksiTextField;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JTextField totalBiayaTextField;
    private javax.swing.JLabel umurPasienLabel;
    private javax.swing.JTextField umurPasienTextField;
    // End of variables declaration//GEN-END:variables
}
