/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.DokterControl;
import control.TransaksiControl;
import control.PasienControl;
import control.RuanganControl;
import control.DepartmentControl;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Dokter;
import model.Transaksi;
import model.Pasien;
import model.Ruangan;
import model.Department;
import model.Jenis_Penyakit;
import table.TableTransaksi;

/**
 * Kelompok 5 :
 * 200710534 - Nicholas Suharto
 * 200710587 - Aldyo Putra
 * 200710607 - Henry
 * 200710653 - Tia Vianka Yustin
 * 200710681 - Kenneth Vincentius Theys
**/
public class TransaksiView extends javax.swing.JFrame {
    
//    private ComputerControl computerControl;
//    private TransaksiControl transaksiControl;
//    private PembeliControl pembeliControl;
//    String action = null;
//    List<Computer> listComputer;
//    List<Pembeli> listPembeli;
//    int selectedId = 0;
//    
//    public Transaksi2() {
//        initComponents();
//        setComponent(false);
//        setEditDeleteBtn(false);
//        computerControl = new ComputerControl();
//        transaksiControl = new TransaksiControl();
//        pembeliControl = new PembeliControl();
//        showTransaksi();
//        setComputerToDropdown();
//        setPembeliToDropdown();
//    }
//    
//    public void setComputerToDropdown() {
//        listComputer = computerControl.showListAllComputer();
//        
//        for(int i=0 ; i < listComputer.size() ; i++) {
//            computerDropdown.addItem(listComputer.get(i));
//        }
//    }
//    
//    public void setPembeliToDropdown() {
//        listPembeli = pembeliControl.showListPembeli();
//        
//        for(int i=0 ; i < listPembeli.size() ; i++) {
//            pembeliDropdown.addItem(listPembeli.get(i));
//        }
//    }
//    
//    public void setComponent(boolean value) {
//        tanggalInput.setEnabled(value);
//        hargaInput.setEnabled(value);
//        computerDropdown.setEnabled(value);
//        pembeliDropdown.setEnabled(value);
//        mouseCheckBox.setEnabled(value);
//        tasCheckBox.setEnabled(value);
//        mousepadCheckBox.setEnabled(value);
//        
//        saveBtn.setEnabled(value);
//        cancelBtn.setEnabled(value);
//    }
//    
//    public void setEditDeleteBtn(boolean value) {
//        updateBtn.setEnabled(value);
//        deleteBtn.setEnabled(value);
//    }
//    
//    public void clearText() {
//        tanggalInput.setText("");
//        hargaInput.setText("");
//        computerDropdown.setSelectedItem(ABORT);
//        pembeliDropdown.setSelectedItem(ABORT);
//        mouseCheckBox.setSelected(false);
//        tasCheckBox.setSelected(false);
//        mousepadCheckBox.setSelected(false);
//        
//        searchInput.setText("");
//    }
//    
//    public void showTransaksi() {
//        tableTransaksi.setModel(transaksiControl.showDataTransaksi(""));
//    }
//    
//    public void inputKosongException() throws InputKosongException {
//        if(computerDropdown.getSelectedIndex() == -1 || pembeliDropdown.getSelectedIndex() == -1 ||
//                tanggalInput.getText().isEmpty() || hargaInput.getText().isEmpty()) {
//            throw new InputKosongException();
//        }
//    }
//    
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        headerPanel = new javax.swing.JPanel();
        storePanel = new javax.swing.JPanel();
        RSLabel = new javax.swing.JLabel();
        judulPanel = new javax.swing.JPanel();
        mouseclickPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        dokterPanel = new javax.swing.JPanel();
        dokterLabel = new javax.swing.JLabel();
        pasienPanel = new javax.swing.JPanel();
        pasienLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        tableContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        systemPanel = new javax.swing.JPanel();
        commandContainer = new javax.swing.JPanel();
        commandBox = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        formContainer = new javax.swing.JPanel();
        formBox = new javax.swing.JPanel();
        leftGrid = new javax.swing.JPanel();
        namapasLabel = new javax.swing.JLabel();
        umurpasLabel = new javax.swing.JLabel();
        genderpasLabel = new javax.swing.JLabel();
        idtranLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showIdTran = new javax.swing.JTextArea();
        tgltranLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        showTglTran = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        showNamaP = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        showUmurP = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        showGenderP = new javax.swing.JTextArea();
        notelppasLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        showNoTelpP = new javax.swing.JTextArea();
        alamatpasLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        showAlamatP = new javax.swing.JTextArea();
        rightGrid = new javax.swing.JPanel();
        bdiagnosisLabel = new javax.swing.JLabel();
        bkamarLabel = new javax.swing.JLabel();
        bdokterLabel = new javax.swing.JLabel();
        namadokLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showNamaD = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        showBiayaD = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        showBiayaDg = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        showBiayaK = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        showTotal = new javax.swing.JTextArea();
        totalBiayaLabel = new javax.swing.JLabel();
        identityPanel = new javax.swing.JPanel();
        identityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setForeground(new java.awt.Color(0, 0, 0));

        storePanel.setBackground(new java.awt.Color(0, 204, 204));
        storePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        storePanel.setForeground(new java.awt.Color(0, 0, 0));

        RSLabel.setBackground(new java.awt.Color(0, 204, 204));
        RSLabel.setFont(new java.awt.Font("Castellar", 0, 22)); // NOI18N
        RSLabel.setForeground(new java.awt.Color(0, 0, 0));
        RSLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RSLabel.setText("rumah sakit");

        javax.swing.GroupLayout storePanelLayout = new javax.swing.GroupLayout(storePanel);
        storePanel.setLayout(storePanelLayout);
        storePanelLayout.setHorizontalGroup(
            storePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        storePanelLayout.setVerticalGroup(
            storePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        judulPanel.setBackground(new java.awt.Color(0, 204, 204));
        judulPanel.setForeground(new java.awt.Color(0, 0, 0));

        mouseclickPanel.setBackground(new java.awt.Color(0, 204, 204));
        mouseclickPanel.setForeground(new java.awt.Color(0, 0, 0));
        mouseclickPanel.setLayout(new java.awt.GridLayout(1, 0));

        adminPanel.setBackground(new java.awt.Color(0, 255, 153));
        adminPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adminPanel.setForeground(new java.awt.Color(0, 0, 0));
        adminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelMouseClicked(evt);
            }
        });

        adminLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(0, 0, 0));
        adminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/computer.png"))); // NOI18N
        adminLabel.setText("Admin");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(adminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(adminLabel)
                .addGap(14, 14, 14))
        );

        mouseclickPanel.add(adminPanel);

        dokterPanel.setBackground(new java.awt.Color(0, 255, 153));
        dokterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dokterPanel.setForeground(new java.awt.Color(0, 0, 0));

        dokterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        dokterLabel.setForeground(new java.awt.Color(0, 0, 0));
        dokterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dokterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/transaksi.png"))); // NOI18N
        dokterLabel.setText("Dokter");

        javax.swing.GroupLayout dokterPanelLayout = new javax.swing.GroupLayout(dokterPanel);
        dokterPanel.setLayout(dokterPanelLayout);
        dokterPanelLayout.setHorizontalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(dokterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        dokterPanelLayout.setVerticalGroup(
            dokterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dokterPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(dokterLabel)
                .addGap(15, 15, 15))
        );

        mouseclickPanel.add(dokterPanel);

        pasienPanel.setBackground(new java.awt.Color(0, 255, 153));
        pasienPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pasienPanel.setForeground(new java.awt.Color(0, 0, 0));
        pasienPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasienPanelMouseClicked(evt);
            }
        });

        pasienLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        pasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        pasienLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets_icon_B/pembeli.png"))); // NOI18N
        pasienLabel.setText("Pasien");

        javax.swing.GroupLayout pasienPanelLayout = new javax.swing.GroupLayout(pasienPanel);
        pasienPanel.setLayout(pasienPanelLayout);
        pasienPanelLayout.setHorizontalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        pasienPanelLayout.setVerticalGroup(
            pasienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pasienPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pasienLabel)
                .addGap(14, 14, 14))
        );

        mouseclickPanel.add(pasienPanel);

        judulLabel.setBackground(new java.awt.Color(0, 204, 204));
        judulLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(0, 0, 0));
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("TRANSAKSI");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mouseclickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mouseclickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(storePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(storePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containerPanel.setBackground(new java.awt.Color(204, 204, 204));
        containerPanel.setForeground(new java.awt.Color(0, 0, 0));

        tableContainer.setBackground(new java.awt.Color(204, 204, 204));

        tableTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        tableTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        javax.swing.GroupLayout tableContainerLayout = new javax.swing.GroupLayout(tableContainer);
        tableContainer.setLayout(tableContainerLayout);
        tableContainerLayout.setHorizontalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tableContainerLayout.setVerticalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        systemPanel.setBackground(new java.awt.Color(204, 204, 204));
        systemPanel.setForeground(new java.awt.Color(0, 0, 0));

        commandContainer.setBackground(new java.awt.Color(204, 204, 204));

        commandBox.setBackground(new java.awt.Color(255, 255, 255));
        commandBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Command", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        commandBox.setForeground(new java.awt.Color(0, 0, 0));

        addBtn.setBackground(new java.awt.Color(0, 255, 204));
        addBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 255, 0));
        updateBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 0, 0));
        updateBtn.setText("Ubah");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 153, 153));
        deleteBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 102, 255));
        cancelBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 204, 255));
        saveBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandBoxLayout = new javax.swing.GroupLayout(commandBox);
        commandBox.setLayout(commandBoxLayout);
        commandBoxLayout.setHorizontalGroup(
            commandBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandBoxLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(commandBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        commandBoxLayout.setVerticalGroup(
            commandBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout commandContainerLayout = new javax.swing.GroupLayout(commandContainer);
        commandContainer.setLayout(commandContainerLayout);
        commandContainerLayout.setHorizontalGroup(
            commandContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(commandBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        commandContainerLayout.setVerticalGroup(
            commandContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandContainerLayout.createSequentialGroup()
                .addComponent(commandBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        formContainer.setBackground(new java.awt.Color(0, 0, 0));

        formBox.setBackground(new java.awt.Color(255, 255, 255));
        formBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        formBox.setForeground(new java.awt.Color(0, 0, 0));
        formBox.setLayout(new java.awt.GridLayout(1, 0));

        leftGrid.setBackground(new java.awt.Color(255, 255, 255));

        namapasLabel.setBackground(new java.awt.Color(255, 255, 255));
        namapasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        namapasLabel.setForeground(new java.awt.Color(0, 0, 0));
        namapasLabel.setText("Nama Pasien");

        umurpasLabel.setBackground(new java.awt.Color(255, 255, 255));
        umurpasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        umurpasLabel.setForeground(new java.awt.Color(0, 0, 0));
        umurpasLabel.setText("Umur Pasien");

        genderpasLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderpasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        genderpasLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderpasLabel.setText("Gender");

        idtranLabel.setBackground(new java.awt.Color(255, 255, 255));
        idtranLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        idtranLabel.setForeground(new java.awt.Color(0, 0, 0));
        idtranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idtranLabel.setText("Id Transaksi");

        showIdTran.setBackground(new java.awt.Color(255, 255, 255));
        showIdTran.setColumns(20);
        showIdTran.setForeground(new java.awt.Color(0, 0, 0));
        showIdTran.setRows(5);
        jScrollPane2.setViewportView(showIdTran);

        tgltranLabel.setBackground(new java.awt.Color(255, 255, 255));
        tgltranLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tgltranLabel.setForeground(new java.awt.Color(0, 0, 0));
        tgltranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgltranLabel.setText("Tgl Transaksi");

        showTglTran.setBackground(new java.awt.Color(255, 255, 255));
        showTglTran.setColumns(20);
        showTglTran.setForeground(new java.awt.Color(0, 0, 0));
        showTglTran.setRows(5);
        jScrollPane4.setViewportView(showTglTran);

        showNamaP.setBackground(new java.awt.Color(255, 255, 255));
        showNamaP.setColumns(20);
        showNamaP.setForeground(new java.awt.Color(0, 0, 0));
        showNamaP.setRows(5);
        jScrollPane5.setViewportView(showNamaP);

        showUmurP.setBackground(new java.awt.Color(255, 255, 255));
        showUmurP.setColumns(20);
        showUmurP.setForeground(new java.awt.Color(0, 0, 0));
        showUmurP.setRows(5);
        jScrollPane6.setViewportView(showUmurP);

        showGenderP.setBackground(new java.awt.Color(255, 255, 255));
        showGenderP.setColumns(20);
        showGenderP.setForeground(new java.awt.Color(0, 0, 0));
        showGenderP.setRows(5);
        jScrollPane7.setViewportView(showGenderP);

        notelppasLabel.setBackground(new java.awt.Color(255, 255, 255));
        notelppasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        notelppasLabel.setForeground(new java.awt.Color(0, 0, 0));
        notelppasLabel.setText("No Telepon");

        showNoTelpP.setBackground(new java.awt.Color(255, 255, 255));
        showNoTelpP.setColumns(20);
        showNoTelpP.setForeground(new java.awt.Color(0, 0, 0));
        showNoTelpP.setRows(5);
        jScrollPane8.setViewportView(showNoTelpP);

        alamatpasLabel.setBackground(new java.awt.Color(255, 255, 255));
        alamatpasLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        alamatpasLabel.setForeground(new java.awt.Color(0, 0, 0));
        alamatpasLabel.setText("Alamat");

        showAlamatP.setBackground(new java.awt.Color(255, 255, 255));
        showAlamatP.setColumns(20);
        showAlamatP.setForeground(new java.awt.Color(0, 0, 0));
        showAlamatP.setRows(5);
        jScrollPane9.setViewportView(showAlamatP);

        javax.swing.GroupLayout leftGridLayout = new javax.swing.GroupLayout(leftGrid);
        leftGrid.setLayout(leftGridLayout);
        leftGridLayout.setHorizontalGroup(
            leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addGroup(leftGridLayout.createSequentialGroup()
                        .addGroup(leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtranLabel)
                            .addComponent(tgltranLabel)
                            .addComponent(namapasLabel)
                            .addComponent(umurpasLabel)
                            .addComponent(genderpasLabel)
                            .addComponent(notelppasLabel)
                            .addComponent(alamatpasLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        leftGridLayout.setVerticalGroup(
            leftGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idtranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tgltranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namapasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(umurpasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderpasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notelppasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alamatpasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        formBox.add(leftGrid);

        rightGrid.setBackground(new java.awt.Color(255, 255, 255));

        bdiagnosisLabel.setBackground(new java.awt.Color(255, 255, 255));
        bdiagnosisLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        bdiagnosisLabel.setForeground(new java.awt.Color(0, 0, 0));
        bdiagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bdiagnosisLabel.setText("Biaya Diagnosis");

        bkamarLabel.setBackground(new java.awt.Color(255, 255, 255));
        bkamarLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        bkamarLabel.setForeground(new java.awt.Color(0, 0, 0));
        bkamarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bkamarLabel.setText("Biaya Kamar");

        bdokterLabel.setBackground(new java.awt.Color(255, 255, 255));
        bdokterLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        bdokterLabel.setForeground(new java.awt.Color(0, 0, 0));
        bdokterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bdokterLabel.setText("Biaya Dokter");

        namadokLabel.setBackground(new java.awt.Color(255, 255, 255));
        namadokLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        namadokLabel.setForeground(new java.awt.Color(0, 0, 0));
        namadokLabel.setText("Dokter Pengampu");

        showNamaD.setBackground(new java.awt.Color(255, 255, 255));
        showNamaD.setColumns(20);
        showNamaD.setForeground(new java.awt.Color(0, 0, 0));
        showNamaD.setRows(5);
        jScrollPane3.setViewportView(showNamaD);

        showBiayaD.setBackground(new java.awt.Color(255, 255, 255));
        showBiayaD.setColumns(20);
        showBiayaD.setForeground(new java.awt.Color(0, 0, 0));
        showBiayaD.setRows(5);
        jScrollPane10.setViewportView(showBiayaD);

        showBiayaDg.setBackground(new java.awt.Color(255, 255, 255));
        showBiayaDg.setColumns(20);
        showBiayaDg.setForeground(new java.awt.Color(0, 0, 0));
        showBiayaDg.setRows(5);
        jScrollPane11.setViewportView(showBiayaDg);

        showBiayaK.setBackground(new java.awt.Color(255, 255, 255));
        showBiayaK.setColumns(20);
        showBiayaK.setForeground(new java.awt.Color(0, 0, 0));
        showBiayaK.setRows(5);
        jScrollPane12.setViewportView(showBiayaK);

        showTotal.setBackground(new java.awt.Color(255, 255, 255));
        showTotal.setColumns(20);
        showTotal.setForeground(new java.awt.Color(0, 0, 0));
        showTotal.setRows(5);
        jScrollPane13.setViewportView(showTotal);

        totalBiayaLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalBiayaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        totalBiayaLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalBiayaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBiayaLabel.setText("TOTAL BIAYA");

        javax.swing.GroupLayout rightGridLayout = new javax.swing.GroupLayout(rightGrid);
        rightGrid.setLayout(rightGridLayout);
        rightGridLayout.setHorizontalGroup(
            rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane10)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane12)
                    .addGroup(rightGridLayout.createSequentialGroup()
                        .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bkamarLabel)
                            .addComponent(bdiagnosisLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(rightGridLayout.createSequentialGroup()
                        .addGroup(rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namadokLabel)
                            .addComponent(bdokterLabel))
                        .addContainerGap(267, Short.MAX_VALUE))
                    .addComponent(totalBiayaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane13)))
        );
        rightGridLayout.setVerticalGroup(
            rightGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namadokLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bkamarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(bdokterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bdiagnosisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(totalBiayaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        formBox.add(rightGrid);

        javax.swing.GroupLayout formContainerLayout = new javax.swing.GroupLayout(formContainer);
        formContainer.setLayout(formContainerLayout);
        formContainerLayout.setHorizontalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formContainerLayout.setVerticalGroup(
            formContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout systemPanelLayout = new javax.swing.GroupLayout(systemPanel);
        systemPanel.setLayout(systemPanelLayout);
        systemPanelLayout.setHorizontalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemPanelLayout.createSequentialGroup()
                .addComponent(commandContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        systemPanelLayout.setVerticalGroup(
            systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(systemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commandContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(systemPanelLayout.createSequentialGroup()
                        .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        identityPanel.setBackground(new java.awt.Color(0, 204, 204));
        identityPanel.setForeground(new java.awt.Color(0, 0, 0));

        identityLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        identityLabel.setForeground(new java.awt.Color(0, 0, 0));
        identityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identityLabel.setText("Kenneth Vincentius Theys - 200710681 - PBO B");

        javax.swing.GroupLayout identityPanelLayout = new javax.swing.GroupLayout(identityPanel);
        identityPanel.setLayout(identityPanelLayout);
        identityPanelLayout.setHorizontalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        identityPanelLayout.setVerticalGroup(
            identityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(systemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(identityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                .addComponent(systemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelMouseClicked
        ComputerView cv = new ComputerView();
        this.dispose();
        cv.setVisible(true);
    }//GEN-LAST:event_adminPanelMouseClicked

    private void pasienPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasienPanelMouseClicked
        PembeliView pv = new PembeliView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_pasienPanelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);

        clearText();
        action = "Tambah";
        computerDropdown.setSelectedIndex(0);
        pembeliDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        setComponent(true);
        action = "Ubah";
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
            try{
                transaksiControl.deleteDataTransaksi(selectedId);
                clearText();
                showTransaksi();
                setComponent(false);
                setEditDeleteBtn(false);
            }catch (Exception e){
                System.out.println("Error : " + e.getMessage());
            }
            break;

            case 1:

            break;
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            int selectedIndex;
            inputKosongException();

            String b1 = "-,";
            String b2 = "-,";
            String b3 = "-";
            selectedIndex = computerDropdown.getSelectedIndex();
            Computer selectedComputer = listComputer.get(selectedIndex);
            selectedIndex = pembeliDropdown.getSelectedIndex();
            Pembeli selectedPembeli = listPembeli.get(selectedIndex);

            if(mouseCheckBox.isSelected()){ b1 = "Mouse, "; }
            if(tasCheckBox.isSelected()){ b2 = "Tas, "; }
            if(mousepadCheckBox.isSelected()){ b3 = "Mousepad"; }

            if(action.equals("Tambah")){
                Transaksi tr = new Transaksi(selectedId,tanggalInput.getText(),hargaInput.getText(),
                    b1+b2+b3, selectedComputer, selectedPembeli);
                transaksiControl.insertDataTransaksi(tr);
            }
            else
            {
                Transaksi tr = new Transaksi(selectedId,tanggalInput.getText(),hargaInput.getText(),
                    b1+b2+b3, selectedComputer, selectedPembeli);
                transaksiControl.updateDataTransaksi(tr);
            }
        } catch(InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
        clearText();
        showTransaksi();
        setComponent(false);

        setEditDeleteBtn(false);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        int indexComputer = -1;
        int indexPembeli = -1;
        setEditDeleteBtn(true);

        setComponent(false);

        int clickedRow = tableTransaksi.getSelectedRow();
        TableModel tableModel = tableTransaksi.getModel();

        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
        tanggalInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        hargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());

        String bonus = tableModel.getValueAt(clickedRow, 5).toString();
        if((bonus.substring(0,1).equals("-")) == false)
        {
            mouseCheckBox.setSelected(true);
        }
        if(bonus.contains("Tas"))
        {
            tasCheckBox.setSelected(true);
        }
        if(bonus.contains("Mousepad"))
        {
            mousepadCheckBox.setSelected(true);
        }

        String id_c = tableModel.getValueAt(clickedRow, 9).toString();
        for(Computer computer : listComputer){
            if(computer.getID().equals(id_c)) {
                indexComputer = listComputer.indexOf(computer);
            }
        }
        computerDropdown.setSelectedIndex(indexComputer);

        String id_p = tableModel.getValueAt(clickedRow, 10).toString();
        for(Pembeli pembeli : listPembeli){
            if(pembeli.getId() == Integer.parseInt(id_p)) {
                indexPembeli = listPembeli.indexOf(pembeli);
            }
        }
        pembeliDropdown.setSelectedIndex(indexPembeli);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RSLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel alamatpasLabel;
    private javax.swing.JLabel bdiagnosisLabel;
    private javax.swing.JLabel bdokterLabel;
    private javax.swing.JLabel bkamarLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel commandBox;
    private javax.swing.JPanel commandContainer;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel dokterLabel;
    private javax.swing.JPanel dokterPanel;
    private javax.swing.JPanel formBox;
    private javax.swing.JPanel formContainer;
    private javax.swing.JLabel genderpasLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel identityLabel;
    private javax.swing.JPanel identityPanel;
    private javax.swing.JLabel idtranLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JPanel leftGrid;
    private javax.swing.JPanel mouseclickPanel;
    private javax.swing.JLabel namadokLabel;
    private javax.swing.JLabel namapasLabel;
    private javax.swing.JLabel notelppasLabel;
    private javax.swing.JLabel pasienLabel;
    private javax.swing.JPanel pasienPanel;
    private javax.swing.JPanel rightGrid;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextArea showAlamatP;
    private javax.swing.JTextArea showBiayaD;
    private javax.swing.JTextArea showBiayaDg;
    private javax.swing.JTextArea showBiayaK;
    private javax.swing.JTextArea showGenderP;
    private javax.swing.JTextArea showIdTran;
    private javax.swing.JTextArea showNamaD;
    private javax.swing.JTextArea showNamaP;
    private javax.swing.JTextArea showNoTelpP;
    private javax.swing.JTextArea showTglTran;
    private javax.swing.JTextArea showTotal;
    private javax.swing.JTextArea showUmurP;
    private javax.swing.JPanel storePanel;
    private javax.swing.JPanel systemPanel;
    private javax.swing.JPanel tableContainer;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel tgltranLabel;
    private javax.swing.JLabel totalBiayaLabel;
    private javax.swing.JLabel umurpasLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
